version: '3'
services:
    superior_prospects:
        image: superior_prospects
        ports:
            - 3000:3000
        links:
            - "sp_mongo:sp_mongo"

    sp_mongo:
        image: mongo:latest
        ports:
            - 27017:27017
        command: mongod --smallfiles

    mongo_seed:
        image: mongo_seed
        links:
            - sp_mongo