version: '3.1'
services:
    traefik:
        image: traefik:1.6.5
        ports:
            - 80:80
            - 443:443
            # - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - $PWD/certs/:/etc/traefik/certs
            - $PWD/traefik.toml:/etc/traefik/traefik.toml
    client:
        image: shaunfowler/superior-prospects-client:latest
        deploy:
            labels:
                - "traefik.frontend.rule=PathPrefixStrip: /"
                - "traefik.port=3000"
                - "traefik.docker.network=superior_prospects_default"

    api:
        image: shaunfowler/superior-prospects-api:latest
        # command: npm run nodemon
        volumes:
            - ./persistence/uploads:/usr/app/uploads
            # - ./packages/superior-prospects-api/:/usr/app
        secrets:
            - sp_client_id
            - sp_client_secret
        environment:
            - API_BASE_URL=http://${DOMAIN:-localhost}/api
        deploy:
            labels:
                - "traefik.frontend.rule=PathPrefixStrip: /api"
                - "traefik.port=4000"
                - "traefik.docker.network=superior_prospects_default"

    mongo:
        image: mongo:4.0
        command: mongod --smallfiles --bind_ip 0.0.0.0
        volumes:
            - "./persistence/mongodata/:/data/db"

secrets:
    sp_client_id:
        external: true
    sp_client_secret:
        external: true
