version: '3.1'
services:
    mongo:
        image: mongo:4.0
        command: mongod --smallfiles --bind_ip 0.0.0.0
        ports:
            - '27017:27017'
        volumes:
            - "./persistence/mongodata/:/data/db"
            - "./api/mock/:/mock"