// Properties

export const PROPERTIES_REQUEST = "PROPERTIES_REQUEST";
export const PROPERTIES_FAILURE = "PROPERTIES_FAILURE";
export const GET_PROPERTIES_SUCCESS = "GET_PROPERTIES_SUCCESS";
export const GET_PROPERTY_SUCCESS = "GET_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const ADD_PROPERTY_SUCCESS = "ADD_PROPERTY_SUCCESS";

// Locations

export const LOCATIONS_REQUEST = "LOCATIONS_REQUEST";
export const LOCATIONS_FAILURE = "LOCATIONS_FAILURE";
export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";

// User

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
