export const GET_UPDATES_REQUEST = "GET_UPDATES_REQUEST";
export const GET_UPDATES_SUCCESS = "GET_UPDATES_SUCCESS";
export const GET_UPDATES_FAILURE = "GET_UPDATES_FAILURE";

export const DELETE_UPDATE_REQUEST = "DELETE_UPDATE_REQUEST";
export const DELETE_UPDATE_SUCCESS = "DELETE_UPDATE_SUCCESS";
export const DELETE_UPDATE_FAILURE = "DELETE_UPDATE_FAILURE";

export const ADD_UPDATE_REQUEST = "ADD_UPDATE_REQUEST";
export const ADD_UPDATE_SUCCESS = "ADD_UPDATE_SUCCESS";
export const ADD_UPDATE_FAILURE = "ADD_UPDATE_FAILURE";
