version: 2

jobs:
  build:
    machine: true      
    working_directory: ~/superior-prospects
    steps:
      - checkout

      - run: 
          name: Restore npm packages
          command: npm install

      - run:
          name: Build
          command: npm run build

      - run:
          name: Test
          command: npm run test