version: 2

jobs:
  build:
    machine: true      
    working_directory: ~/superior-prospects
    steps:
      - checkout

      - run: 
          name: Restore npm packages
          command: npm install

      - run:
          name: Restore bower packages
          command: npm run bower-install

      - run:
          name: Gulp build
          command: npm run build

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Tests
          command: npm run test